name: Docker Image CI

on:
  push:
    branches: [ "browninfosecguy/k8Project" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
